implement started, pending, ended runs

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -4,13 +4,6 @@ if ! command -v bundle > /dev/null; then
   source ~/.zshrc
 fi
 
-bundle exec rspec
-RC=$?
-if [ ! $RC -eq 0 ]; then
-  echo 'specs are not running, commit aborted!'
-  exit 1
-fi
-
 bundle exec rubocop -a -D -c .rubocop.yml
 RC=$?
 if [ ! $RC -eq 0 ]; then
@@ -39,3 +32,9 @@ if [ ! $RC -eq 0 ]; then
   exit 1
 fi
 
+bundle exec rspec
+RC=$?
+if [ ! $RC -eq 0 ]; then
+  echo 'specs are not running, commit aborted!'
+  exit 1
+fi
